const N=9, canvas=document.querySelector('#board'), ctx=canvas.getContext('2d');
const rivals=[
 {name:'ハムすけ',image:'assets/characters/hamster.png',title:'はじめて',stars:1,skill:.12,intro:'ゆっくり一緒に考えよう。すみから始めると、陣地を作りやすいよ。'},
 {name:'月うさぎ',image:'assets/characters/rabbit.png',title:'やさしい',stars:2,skill:.28,intro:'石をつなげる練習をしよう。ひとりぼっちの石を作らないのがコツだよ。'},
 {name:'ミーカ先生',image:'assets/characters/meerkat.png',title:'ふつう',stars:3,skill:.48,intro:'相手の呼吸点にも注目してみよう。取れる石を一緒に探すよ。'},
 {name:'マモ親方',image:'assets/characters/marmot.png',title:'つよい',stars:4,skill:.7,intro:'守る手と攻める手、両方の意味を考えてみよう。'},
 {name:'囲碁仙人',image:'assets/characters/sage.png',title:'とてもつよい',stars:5,skill:.92,intro:'よい手には理由がある。局面全体を見ながら、わしが手ほどきしよう。'}
];
let board=emptyBoard(), history=[], currentRival=0, thinking=false, captures=[0,0], learned=0, sound=true, lastMove=null, hintPoint=null, passes=0, gameOver=false;
function emptyBoard(){return Array.from({length:N},()=>Array(N).fill(0))}
function renderRivals(){
 const list=document.querySelector('#opponentList'); list.innerHTML='';
 rivals.forEach((r,i)=>{const b=document.createElement('button');b.className='opponent'+(i===currentRival?' active':'');b.innerHTML=`<span class="avatar"><img src="${r.image}" alt="${r.name}"></span><span><b>${r.name}</b><small>${r.title}</small></span><span class="stars">${[1,2,3,4,5].map(x=>`<span class="${x<=r.stars?'on':''}">●</span>`).join('')}</span>`;b.onclick=()=>selectRival(i);list.append(b)})
}
function selectRival(i){currentRival=i;const r=rivals[i];renderRivals();['rivalName','coachName'].forEach(id=>document.querySelector('#'+id).textContent=r.name);document.querySelector('#rivalTitle').textContent=r.title;['rivalAvatar','coachAvatar'].forEach(id=>{document.querySelector('#'+id).src=r.image;document.querySelector('#'+id).alt=r.name});say(r.intro,'あいさつ')}
function xy(e){const r=canvas.getBoundingClientRect(), pad=40, size=canvas.width-pad*2;return [Math.round(((e.clientX-r.left)*canvas.width/r.width-pad)/(size/(N-1))),Math.round(((e.clientY-r.top)*canvas.height/r.height-pad)/(size/(N-1)))]}
function neighbors(x,y){return [[x-1,y],[x+1,y],[x,y-1],[x,y+1]].filter(([a,b])=>a>=0&&b>=0&&a<N&&b<N)}
function groupAt(b,x,y){const color=b[y][x], seen=new Set(), stack=[[x,y]], stones=[], libs=new Set();while(stack.length){const [a,c]=stack.pop(),k=a+','+c;if(seen.has(k))continue;seen.add(k);stones.push([a,c]);neighbors(a,c).forEach(([nx,ny])=>{if(!b[ny][nx])libs.add(nx+','+ny);else if(b[ny][nx]===color)stack.push([nx,ny])})}return {stones,libs}}
function tryMove(source,x,y,color){if(x<0||y<0||x>=N||y>=N||source[y][x])return null;const b=source.map(r=>r.slice());b[y][x]=color;let taken=0;neighbors(x,y).forEach(([nx,ny])=>{if(b[ny][nx]===3-color){const g=groupAt(b,nx,ny);if(!g.libs.size){taken+=g.stones.length;g.stones.forEach(([a,c])=>b[c][a]=0)}}});if(!groupAt(b,x,y).libs.size)return null;return {board:b,taken}}
canvas.addEventListener('click',e=>{if(thinking)return;const [x,y]=xy(e);playHuman(x,y)});
function playHuman(x,y){if(gameOver)return toast('対局は終了しています。「もう一局」を選んでね');const m=tryMove(board,x,y,1);if(!m){if(hintPoint&&hintPoint[0]===x&&hintPoint[1]===y){hintPoint=bestHint();draw();say('盤面が変わったので、置ける場所へヒントを更新したよ。新しい葉っぱの輪を見てね。','ヒントを更新')}else say('そこには置けないよ。石は空いている交点に置き、自分の呼吸点を残そう。','置けない手');return}save();board=m.board;captures[0]+=m.taken;lastMove=[x,y];hintPoint=null;passes=0;updateStats();draw();coachHumanMove(x,y,m.taken);setTimeout(aiTurn,520)}
function save(){history.push({board:board.map(r=>r.slice()),captures:[...captures],lastMove:lastMove&&[...lastMove]});if(history.length>20)history.shift()}
function aiTurn(){thinking=true;document.querySelector('#thinking').classList.add('show');setTurn(false);setTimeout(()=>{if(passes===1){thinking=false;document.querySelector('#thinking').classList.remove('show');passes=2;say(`${rivals[currentRival].name}もパスしたよ。両方が続けてパスしたので対局は終わりです。`,'終局');finishGame();return}const moves=[];for(let y=0;y<N;y++)for(let x=0;x<N;x++){const m=tryMove(board,x,y,2);if(m){let score=m.taken*30+neighbors(x,y).filter(([a,b])=>board[b][a]===2).length*3+neighbors(x,y).filter(([a,b])=>board[b][a]===1).length*2;score+=(4-Math.abs(4-x))*.3+(4-Math.abs(4-y))*.3+Math.random()*18*(1-rivals[currentRival].skill);moves.push({x,y,m,score})}}moves.sort((a,b)=>b.score-a.score);const filled=board.flat().filter(Boolean).length/(N*N);if(!moves.length||filled>.72&&Math.random()<.45){thinking=false;document.querySelector('#thinking').classList.remove('show');passes=1;setTurn(true);say(`${rivals[currentRival].name}がパスしたよ。あなたも置く場所がなければ「パス・終局」を押そう。`,'相手がパス');return}const pick=moves[Math.floor(Math.random()*Math.min(moves.length,Math.max(1,Math.round(8*(1-rivals[currentRival].skill)))))]||moves[0];if(pick){save();board=pick.m.board;captures[1]+=pick.m.taken;lastMove=[pick.x,pick.y];passes=0}thinking=false;document.querySelector('#thinking').classList.remove('show');setTurn(true);updateStats();draw();if(pick?.m.taken)say(`${rivals[currentRival].name}が石を${pick.m.taken}個取ったよ。でも大丈夫。取られた理由を盤で見つけるのが上達への近道だよ。`,'取られた石');else coachPosition()},420+currentRival*100)}
function coachHumanMove(x,y,taken){if(taken){learn('アタリ');say(`やったね！ 白石を${taken}個取ったよ。最後の呼吸点をふさいだのが決め手だね。`,'とてもよい手');return}const g=groupAt(board,x,y);if(g.libs.size===1){learn('呼吸点');say('その石は「アタリ」だよ。呼吸点があと1つしかないから、次は逃げ道を広げよう。','気をつけて');return}const friendly=neighbors(x,y).some(([a,b])=>board[b][a]===1);if(friendly){learn('つながる');say('石がつながったね。つながった石は呼吸点を分け合えるから、取られにくくなるよ。','よい形')}else if((x<=2||x>=6)&&(y<=2||y>=6))say('すみに置けたね。盤の端を壁として使えるから、少ない石で陣地を作りやすいよ。','よい一手');else say(`この石には呼吸点が${g.libs.size}つあるよ。次は近くに仲間を置くと安心だね。`,'いまの形')}
function coachPosition(){let danger=false;outer:for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(board[y][x]===1&&groupAt(board,x,y).libs.size===1){danger=true;break outer}if(danger)say('黒石にアタリがあるよ。「次の一手を教えて」を押すと、逃げ道を光で示すね。','相手が打ったあと');else say('相手も置いたよ。相手の石を囲むより、まず自分の石をつなぐ手を探してみよう。','あなたの番')}
function bestHint(){const checked=new Set();for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(board[y][x]===1){const g=groupAt(board,x,y);if(g.libs.size===1){const [p]=g.libs;if(!checked.has(p)){checked.add(p);const point=p.split(',').map(Number);if(tryMove(board,point[0],point[1],1))return point}}}const corners=[[2,2],[6,2],[2,6],[6,6],[4,4]];return corners.find(([x,y])=>tryMove(board,x,y,1))||randomLegal(1)}
function randomLegal(c){const a=[];for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(tryMove(board,x,y,c))a.push([x,y]);return a[Math.floor(Math.random()*a.length)]}
document.querySelector('#hintBtn').onclick=()=>{hintPoint=bestHint();draw();if(hintPoint)say('葉っぱの輪がついた場所がおすすめ。石を助けるか、すみを広げられる一手だよ。','次の一手');else say('もう置ける場所がないようだね。ここではパスを選ぼう。','置ける場所なし')};
document.querySelector('#undoBtn').onclick=()=>{if(thinking||!history.length)return toast('まだ戻せる手がないよ');const h=history.length>=2?history.splice(-2)[0]:history.pop();board=h.board;captures=h.captures;lastMove=h.lastMove;hintPoint=null;updateStats();draw();setTurn(true);say('一手戻したよ。別の場所を試してみよう。','やり直し')};
document.querySelector('#passBtn').onclick=()=>{if(thinking)return;passes++;say('パスしたよ。相手もパスすると対局が終わります。','パス');if(passes>=2)finishGame();else aiTurn()};
function scoreGame(){const seen=new Set(),territory=[0,0];for(let y=0;y<N;y++)for(let x=0;x<N;x++){const key=x+','+y;if(board[y][x]||seen.has(key))continue;const region=[],border=new Set(),stack=[[x,y]];while(stack.length){const [a,b]=stack.pop(),k=a+','+b;if(seen.has(k))continue;seen.add(k);region.push([a,b]);neighbors(a,b).forEach(([nx,ny])=>{if(board[ny][nx])border.add(board[ny][nx]);else if(!seen.has(nx+','+ny))stack.push([nx,ny])})}if(border.size===1)territory[[...border][0]-1]+=region.length}return {black:territory[0]+captures[0],white:territory[1]+captures[1]+6.5,territory}}
function finishGame(){gameOver=true;thinking=false;document.querySelector('#thinking').classList.remove('show');const s=scoreGame(),blackWins=s.black>s.white,margin=Math.abs(s.black-s.white).toFixed(1);document.querySelector('#dialogTitle').textContent=blackWins?'あなたの勝ち！':'今回は相手の勝ち';document.querySelector('#dialogContent').innerHTML=`<div class="lesson-steps"><div class="lesson-step"><i>黒</i><div><b>あなた　${s.black}目</b><p>陣地 ${s.territory[0]} ＋ 取った石 ${captures[0]}</p></div></div><div class="lesson-step"><i>白</i><div><b>${rivals[currentRival].name}　${s.white}目</b><p>陣地 ${s.territory[1]} ＋ 取った石 ${captures[1]} ＋ コミ 6.5</p></div></div><div class="lesson-step"><i>差</i><div><b>${margin}目差</b><p>練習用の簡易集計です。白には先に打つ黒との公平さを保つ「コミ」が付きます。</p></div></div><button class="board-actions primary" id="newGameBtn">同じ相手ともう一局</button>`;document.querySelector('#newGameBtn').onclick=startNewGame;document.querySelector('#lessonDialog').showModal()}
function startNewGame(){board=emptyBoard();history=[];captures=[0,0];lastMove=null;hintPoint=null;passes=0;gameOver=false;updateStats();draw();setTurn(true);document.querySelector('#lessonDialog').close();say('新しい対局だよ。まずは盤のすみから始めてみよう。','もう一局')}
function setTurn(human){document.querySelector('#turnLabel').textContent=human?'あなたの番':`${rivals[currentRival].name}の番`;document.querySelector('#moveLabel').textContent=human?'黒石を置いてね':'少し待ってね'}
function say(msg,tag){document.querySelector('#coachMessage').textContent=msg;document.querySelector('.speech-tag').textContent=tag}
function learn(word){learned=Math.min(3,learned+1);document.querySelector('#lessonCount').textContent=learned+' / 3';[...document.querySelectorAll('#learnedList li')].slice(0,learned).forEach(x=>x.classList.remove('locked'))}
function updateStats(){document.querySelector('#blackCaps').textContent=captures[0];document.querySelector('#whiteCaps').textContent=captures[1]}
function draw(){const W=canvas.width,p=40,s=(W-p*2)/(N-1);ctx.clearRect(0,0,W,W);ctx.strokeStyle='#60431e';ctx.lineWidth=2;for(let i=0;i<N;i++){ctx.beginPath();ctx.moveTo(p,p+i*s);ctx.lineTo(W-p,p+i*s);ctx.stroke();ctx.beginPath();ctx.moveTo(p+i*s,p);ctx.lineTo(p+i*s,W-p);ctx.stroke()}[[2,2],[6,2],[4,4],[2,6],[6,6]].forEach(([x,y])=>{ctx.beginPath();ctx.arc(p+x*s,p+y*s,5,0,Math.PI*2);ctx.fillStyle='#60431e';ctx.fill()});for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(board[y][x]){const cx=p+x*s,cy=p+y*s,r=s*.43,g=ctx.createRadialGradient(cx-r*.35,cy-r*.4,2,cx,cy,r);if(board[y][x]===1){g.addColorStop(0,'#4b5350');g.addColorStop(1,'#101513')}else{g.addColorStop(0,'#fff');g.addColorStop(1,'#d8d9d3')}ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle=g;ctx.shadowColor='rgba(0,0,0,.35)';ctx.shadowBlur=8;ctx.shadowOffsetY=4;ctx.fill();ctx.shadowColor='transparent';if(lastMove&&lastMove[0]===x&&lastMove[1]===y){ctx.beginPath();ctx.arc(cx,cy,5,0,Math.PI*2);ctx.fillStyle=board[y][x]===1?'#fff':'#333';ctx.fill()}}if(hintPoint){const [x,y]=hintPoint,cx=p+x*s,cy=p+y*s;ctx.beginPath();ctx.arc(cx,cy,s*.35,0,Math.PI*2);ctx.strokeStyle='#ecf6a6';ctx.lineWidth=12;ctx.globalAlpha=.85;ctx.stroke();ctx.globalAlpha=1;ctx.beginPath();ctx.arc(cx,cy,s*.48,0,Math.PI*2);ctx.strokeStyle='#608b39';ctx.lineWidth=4;ctx.setLineDash([7,6]);ctx.stroke();ctx.setLineDash([])}}
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
const lessons={komoku:['小目の受け方','小目は、すみをしっかり守りやすい場所です。','相手が近づいたら、はさまずに近くから受けてみよう。','石をつないだら、外側へ伸びて安全な形を作ります。'],hoshi:['星へのカカリ','星はすみと外側をバランスよく見られる場所です。','相手の星に近づく手を「カカリ」と呼びます。','まずは一間に受ける形を覚えれば十分です。'],sanrensei:['石のつながり','上下左右に並んだ同じ色の石は、1つの仲間になります。','斜めはまだつながっていません。相手に切られることがあります。','呼吸点が少なくなったら、外へ伸びて逃げ道を増やそう。']};
function openLesson(key){const d=lessons[key];document.querySelector('#dialogTitle').textContent=d[0];document.querySelector('#dialogContent').innerHTML=`<div class="lesson-steps">${d.slice(1).map((t,i)=>`<div class="lesson-step"><i>${i+1}</i><div><b>${i===0?'どんな形？':i===1?'どう打つ？':'覚えること'}</b><p>${t}</p></div></div>`).join('')}</div>`;document.querySelector('#lessonDialog').showModal()}
document.querySelectorAll('.joseki-card').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));
document.querySelector('#rulesBtn').onclick=()=>{document.querySelector('#dialogTitle').textContent='囲碁のルールは3つだけ';document.querySelector('#dialogContent').innerHTML='<div class="lesson-steps"><div class="lesson-step"><i>1</i><div><b>交点に石を置く</b><p>黒と白が交互に、線が交わる場所へ置きます。一度置いた石は動きません。</p></div></div><div class="lesson-step"><i>2</i><div><b>囲んだ石を取る</b><p>石の上下左右にある空き「呼吸点」を全部ふさぐと、その石を取れます。</p></div></div><div class="lesson-step"><i>3</i><div><b>広く囲んだほうが勝ち</b><p>最後に自分の石で囲んだ場所と、取った石を数えます。最初は石取りだけ楽しめば大丈夫。</p></div></div></div>';document.querySelector('#lessonDialog').showModal()};
document.querySelector('#closeDialog').onclick=()=>document.querySelector('#lessonDialog').close();
document.querySelector('#whyBtn').onclick=()=>{say('囲碁では、石の上下左右にある空きが命綱。これを「呼吸点」と呼ぶよ。呼吸点が多い石ほど取られにくいんだ。','もう少しくわしく');learn('呼吸点')};
document.querySelector('#soundBtn').onclick=()=>{sound=!sound;document.querySelector('#soundBtn span').textContent=sound?'音あり':'音なし';toast(sound?'音をオンにしました':'音をオフにしました')};
renderRivals();selectRival(0);draw();
