import Foundation
import SwiftUI

struct VoiceFeatures: Codable, Equatable {
    var duration: Double
    var averageEnergy: Double
    var peakEnergy: Double
    var averagePitch: Double
    var pitchRange: Double
    var rhythmDensity: Double
    var silenceRatio: Double
    var zeroCrossingRate: Double
    var waveform: [Double]
    var energyCurve: [Double]
    var pitchCurve: [Double]

    static let empty = VoiceFeatures(
        duration: 0,
        averageEnergy: 0,
        peakEnergy: 0,
        averagePitch: 0,
        pitchRange: 0,
        rhythmDensity: 0,
        silenceRatio: 0,
        zeroCrossingRate: 0,
        waveform: [],
        energyCurve: [],
        pitchCurve: []
    )
}

struct VoiceArtwork: Identifiable, Codable, Equatable {
    var id: UUID
    var createdAt: Date
    var title: String
    var seed: UInt64
    var features: VoiceFeatures

    var palette: ArtworkPalette {
        ArtworkPalette(seed: seed, features: features)
    }

    var style: ArtworkStyle {
        ArtworkStyle(seed: seed, features: features)
    }

    var nftMetadata: NFTMetadata {
        NFTMetadata(
            name: title,
            description: "Generated by VoiceprintNFT from a short voice recording. The audio file is not stored. The artwork is created from abstract voice features such as waveform, pitch, rhythm, silence, and energy.",
            image: "ipfs://REPLACE_WITH_IMAGE_CID",
            attributes: [
                NFTAttribute(trait_type: "Duration", value: rounded(features.duration)),
                NFTAttribute(trait_type: "Voice Energy", value: rounded(features.averageEnergy * 100)),
                NFTAttribute(trait_type: "Peak Energy", value: rounded(features.peakEnergy * 100)),
                NFTAttribute(trait_type: "Pitch Range", value: rounded(features.pitchRange)),
                NFTAttribute(trait_type: "Rhythm Density", value: rounded(features.rhythmDensity * 100)),
                NFTAttribute(trait_type: "Silence Pattern", value: rounded(features.silenceRatio * 100)),
                NFTAttribute(trait_type: "Creature Motif", value: Double(style.biomorphIndex)),
                NFTAttribute(trait_type: "Seed", value: Double(seed % 1_000_000))
            ]
        )
    }

    private func rounded(_ value: Double) -> Double {
        (value * 100).rounded() / 100
    }
}

struct NFTMetadata: Codable {
    var name: String
    var description: String
    var image: String
    var attributes: [NFTAttribute]
}

struct NFTAttribute: Codable {
    var trait_type: String
    var value: Double
}

struct ArtworkPalette {
    var backgroundA: Color
    var backgroundB: Color
    var lineA: Color
    var lineB: Color
    var spark: Color

    init(seed: UInt64, features: VoiceFeatures) {
        var rng = SeededRandomNumberGenerator(seed: seed ^ 0xa921_f35d_49c1_7a81)
        let jitter = rng.double(in: -0.18...0.18)
        let baseHue = ((Double(seed % 360) / 360) + features.averagePitch / 900 + jitter).wrappedUnit
        let energy = max(0.35, min(0.95, features.averageEnergy * 4))
        let pitch = max(0.25, min(0.9, features.pitchRange / 280))

        backgroundA = Color(hue: baseHue, saturation: 0.52 + rng.double(in: 0...0.24), brightness: 0.08 + energy * rng.double(in: 0.12...0.24))
        backgroundB = Color(hue: (baseHue + rng.double(in: 0.13...0.42)).wrappedUnit, saturation: 0.38 + pitch * 0.32, brightness: rng.double(in: 0.10...0.24))
        lineA = Color(hue: (baseHue + rng.double(in: 0.29...0.58)).wrappedUnit, saturation: 0.68 + rng.double(in: 0...0.24), brightness: 0.82 + rng.double(in: 0...0.18))
        lineB = Color(hue: (baseHue + rng.double(in: 0.04...0.22)).wrappedUnit, saturation: 0.66 + rng.double(in: 0...0.28), brightness: 0.62 + rng.double(in: 0...0.26))
        spark = Color(hue: (baseHue + rng.double(in: 0.56...0.82)).wrappedUnit, saturation: 0.72 + rng.double(in: 0...0.2), brightness: 0.9 + rng.double(in: 0...0.1))
    }
}

struct ArtworkStyle: Equatable {
    enum Family: String {
        case bloom
        case aurora
        case topography
        case calligraphy
        case mist
        case nebula
        case figure
        case organism
        case spirit
    }

    var family: Family
    var symmetry: Int
    var turbulence: Double
    var strokeBias: Double
    var biomorphIndex: Int

    init(seed: UInt64, features: VoiceFeatures) {
        var rng = SeededRandomNumberGenerator(seed: seed ^ 0xd6e8_feb8_6659_fd93)
        let families: [Family] = [
            .figure, .organism, .spirit,
            .bloom, .organism, .aurora,
            .figure, .topography, .spirit,
            .calligraphy, .organism, .mist,
            .nebula, .figure, .spirit
        ]
        family = families[Int(seed % UInt64(families.count))]
        symmetry = 3 + Int(rng.next() % 9)
        turbulence = min(1.35, 0.34 + features.zeroCrossingRate * 12 + rng.double(in: 0...0.66))
        strokeBias = rng.double(in: 0.65...1.75)
        biomorphIndex = Int((seed ^ UInt64(Int(features.averageEnergy * 10_000))) % 5_000)
    }
}

struct SeededRandomNumberGenerator: RandomNumberGenerator {
    private var state: UInt64

    init(seed: UInt64) {
        state = seed == 0 ? 0x1234abcd : seed
    }

    mutating func next() -> UInt64 {
        state &+= 0x9e3779b97f4a7c15
        var value = state
        value = (value ^ (value >> 30)) &* 0xbf58476d1ce4e5b9
        value = (value ^ (value >> 27)) &* 0x94d049bb133111eb
        return value ^ (value >> 31)
    }

    mutating func double(in range: ClosedRange<Double>) -> Double {
        let unit = Double(next() % 10_000) / 10_000
        return range.lowerBound + (range.upperBound - range.lowerBound) * unit
    }
}

private extension Double {
    var wrappedUnit: Double {
        let value = truncatingRemainder(dividingBy: 1)
        return value < 0 ? value + 1 : value
    }
}

@MainActor
final class ArtworkGallery: ObservableObject {
    @Published private(set) var artworks: [VoiceArtwork] = []

    private let storageKey = "voiceprint.artworks"

    init() {
        load()
    }

    func add(_ artwork: VoiceArtwork) {
        artworks.insert(artwork, at: 0)
        artworks = Array(artworks.prefix(12))
        save()
    }

    func useDemoArtworks(_ demoArtworks: [VoiceArtwork]) {
        artworks = Array(demoArtworks.prefix(12))
        save()
    }

    private func load() {
        guard let data = UserDefaults.standard.data(forKey: storageKey),
              let decoded = try? JSONDecoder().decode([VoiceArtwork].self, from: data) else {
            return
        }
        artworks = decoded
    }

    private func save() {
        guard let data = try? JSONEncoder().encode(artworks) else { return }
        UserDefaults.standard.set(data, forKey: storageKey)
    }
}

enum DemoArtworkFactory {
    static func artworks() -> [VoiceArtwork] {
        [
            make(
                title: "Lunar Mammal #1837",
                seed: 0x9f33_ab12_8831,
                energy: 0.58,
                pitch: 210,
                range: 148,
                rhythm: 2.7,
                silence: 0.18,
                phase: 0.0
            ),
            make(
                title: "Wing Signal #2401",
                seed: 0x71c2_55d9_4a10,
                energy: 0.44,
                pitch: 165,
                range: 92,
                rhythm: 3.4,
                silence: 0.09,
                phase: 0.29
            ),
            make(
                title: "Neon Profile #5082",
                seed: 0xd412_8e01_7723,
                energy: 0.66,
                pitch: 245,
                range: 176,
                rhythm: 1.9,
                silence: 0.24,
                phase: 0.57
            ),
            make(
                title: "Deep Fish #7716",
                seed: 0x8c90_66aa_b351,
                energy: 0.39,
                pitch: 132,
                range: 78,
                rhythm: 2.2,
                silence: 0.32,
                phase: 0.81
            )
        ]
    }

    private static func make(title: String, seed: UInt64, energy: Double, pitch: Double, range: Double, rhythm: Double, silence: Double, phase: Double) -> VoiceArtwork {
        let samples = 160
        let waveform = (0..<samples).map { index in
            let t = Double(index) / Double(samples - 1)
            return sin((t + phase) * .pi * 8) * 0.58 + sin((t + phase * 0.4) * .pi * 23) * 0.22
        }
        let energyCurve = (0..<120).map { index in
            let t = Double(index) / 119
            return max(0.04, min(1, energy + sin((t + phase) * .pi * 6) * 0.25))
        }
        let pitchCurve = (0..<120).map { index in
            let t = Double(index) / 119
            return max(0.05, min(1, 0.45 + sin((t + phase) * .pi * 4) * 0.3))
        }
        return VoiceArtwork(
            id: UUID(),
            createdAt: Date(),
            title: title,
            seed: seed,
            features: VoiceFeatures(
                duration: 5.8,
                averageEnergy: energy,
                peakEnergy: min(1, energy + 0.31),
                averagePitch: pitch,
                pitchRange: range,
                rhythmDensity: rhythm,
                silenceRatio: silence,
                zeroCrossingRate: 0.12 + phase * 0.1,
                waveform: waveform,
                energyCurve: energyCurve,
                pitchCurve: pitchCurve
            )
        )
    }
}
